apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  namespace: demo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        image: faris94/web:2
        ports:
        - containerPort: 3000
      nodeSelector:
        node-role.kubernetes.io/worker: ""